### ISSUE TITLE
PDF文件無法打開

### ISSUE THREAD

**Issue by gwankyun** [MeouSker77/Cpp17#25]
文件已損壞，望修復

**Comment by MeouSker77** [comment]
如果是通过README里的链接直接在github中打开出错的话，可以点击“Download”按钮下载之后在本地打开试试，我这里直接在github中打开也会出错，下载之后在本地打开就没问题。

**Comment by gwankyun** [comment]
> 如果是通过README里的链接直接在github中打开出错的话，可以点击“Download”按钮下载之后在本地打开试试，我这里直接在github中打开也会出错，下载之后在本地打开就没问题。

試了一下，可以了，謝謝解答。
