### ISSUE TITLE
求教Latex的相关资料

### ISSUE THREAD

**Issue by xiaoweiChen** [MeouSker77/Cpp17#7]
很高兴看到这本书的中文翻译，自己也是C++爱好者，也有翻译过关于现代C++的书籍。

不过，我的翻译大多是使用markdown的方式。

这里想求教，是否能分享一下您学习Latex的网站地址，或者是书籍名称？想参考学习一下。

**Comment by MeouSker77** [comment]
以我自己的情况来说的话，系统的学习只有看了刘海洋老师的《LaTex入门》的前三章，学了下基本的文档结构。
后边都是需要什么就直接上网查的，然后有些细节想调整时候都是直接查的文档。

**Comment by xiaoweiChen** [comment]
感谢回复与分享，书籍有空会去找一下来看的。
